### ISSUE TITLE
Where did the option to fit either a flat or sloping background go?

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#10]
The user needs the option to fit either a zeroeth or first order polynomial to the background. Now (I think!!) we only have the option to do first order unless the profile is wrapped. Where did this go? I think a lot of people will want to do a flat background subtraction. @hopehhchen this option currently isn't available in the new version right?

**Comment by hopehhchen** [comment]
I just added it back.  Now `bgdegree` in `fit_profile` controls the order of polynomial used in BG subtraction (22ac574f3c800214c7f1433c0fafa35855fd6cd4).

**Comment by catherinezucker** [comment]
Thanks so much @hopehhchen ! I will have a new plotting feature to unveil today or tomorrow :)
