### ISSUE TITLE
Reverting back to only fitting one function at once option?

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#11]
How opposed would we be to having the option to fit just Gaussian, just Plummer, or both (instead of only both)? I know it doesn't add any extra computational time, but I really think people will want to use different fitting radii for the two, and having two sets of Plummer variables (one with a reasonable fitting radius and one with a less reasonable range) might confuse people, and people will have to keep track of which fit results they want to access. Also I think it would make it easier for plotting. If you're ok with this @hopehhchen I will implement. Thanks!

**Comment by hopehhchen** [comment]
I am starting to see your point.  Can we talk about this after our meeting with Bernie tomorrow?  I just think that we should come up with an easy and clear structure to store the setup parameters and the fitting results before we implement it.  Thank you!

**Comment by catherinezucker** [comment]
Yeah, sure! Do you want to meet together in the Vizelab before or after the call @hopehhchen ?

**Comment by catherinezucker** [comment]
Oh, ok, sounds good! We'll talk about this tomorrow after the meeting with Bernie!!
