### ISSUE TITLE
Peak Finding Error?

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#14]
Hi @hopehhchen. I have been going through some sanity checks comparing new RadFil and old RadFil, and I think there might be a bug (or at least a discrepancy--I could have been wrong the first time!!) with the peak finding algorithm in new RadFil, as the peaks seem more discontinuous. I have attached two screenshots of the filament masks with the cuts and the peak along each cut marked in blue. Even though the cuts are the same (I used the same samp_int=2 and counted them), the peaks in new RadFil are different, and particularly in the bottom left hand corner you see that a lot of the peaks are basically at the very end of the mask and jump around a bit. Would you mind checking this and seeing what's going on and if the max pixels in new RadFil are really at the edge of the mask? We could be offset by a pixel or something. And unlike Musca, since we don't have a ton of cuts with the large-scale filaments, any offset in the peaks like this might be able to account for the different best-fit values between new and old RadFil. Thanks!! I can email you the mask, image, and spine. I am just about finished with the new plotter tool and will commit it tonight. 

[New_RadFil_Version.pdf](https://github.com/catherinezucker/radfil/files/1219293/New_RadFil_Version.pdf)
[Old_RadFil_Version.pdf](https://github.com/catherinezucker/radfil/files/1219292/Old_RadFil_Version.pdf)

**Comment by catherinezucker** [comment]
Here's a better view of the max pixels on the edge of the mask in New RadFil. 
<img width="1032" alt="screen shot 2017-08-11 at 7 40 40 pm" src="https://user-images.githubusercontent.com/18339657/29235484-365581fe-7ecd-11e7-90d7-8400ad115b3b.png">

**Comment by hopehhchen** [comment]
Wow, this looks really bad!  I'll check through the code and find out what could have gone wrong.  Could you post the codes or the setup parameters?  Thanks!

**Comment by catherinezucker** [comment]
I just added the files to a folder called Fil8_Bug_Data. Here is the code you need to reproduce...
###
img,hdr=fits.getdata("./Fil8_Bug_Data/HIGAL_L_Fil8_N.fits",header=True)
mask=fits.getdata("./Fil8_Bug_Data/Fil8_filfind_mask.fits")
filspine=fits.getdata("./Fil8_Bug_Data/Fil8_longpath.fits")
dist=2750.0

radfil=radfil_class.radfil(img,filmask.astype(bool),header=hdr,distance=dist,filspine=filspine)
radfil.build_profile(samp_int = 2, cutdist=5)
radfil.fit_profile(fitdist=4,bgdist=(3,4),fitfunc="Plummer",verbose=True,beamwidth=43.0)
###
I just pushed a lot of changes through so you'll need to git pull first

**Comment by hopehhchen** [comment]
Thanks!

**Comment by hopehhchen** [comment]
The error was in indexing when the profile is extracted in `profile_tools.profile_builder`.  76aeb234ae8dcaee2991428b9c3433f8c689f6ac fixed the error.  It also improves the fitting.  For Musca, the new numbers now agree with the old numbers within 0.1%.  This could have been the reason for discrepancies in the fitted parameters.  Please test and check.  Thanks!

**Comment by catherinezucker** [comment]
Thanks so much, Hope. Looks like you definitely fixed it. I think we are getting very close to the old values (within margin of errors most definitely). Will check more thoroughly this weekend!!

**Comment by catherinezucker** [comment]
Actually, is there any reason why the max column density pixel wouldn't be identical across versions if the same samp_int is used? I know the same samp_int in both versions produces the same number of cuts, but in theory the max column density pixel should be the same too, right?

**Comment by hopehhchen** [comment]
Yes, I think so.  One thing I can think of is the way the new and the old versions filter the cuts that are too close to the ends of the spline.  Could you try to remake the following plot with the old version so we can make sure that the cuts are *exactly* the same?  Thanks!

I think the new peaks are, at least, the right peaks for the new cuts.
![peak_finding_fil8](https://user-images.githubusercontent.com/5449218/29238161-cbb88992-7efc-11e7-9608-4d95eaa2fadb.png)

**Comment by catherinezucker** [comment]
@hopehhchen how did you get the contrast/bias so nice on the colormap? I have this figure for old radfil ready but I can't achieve the optimal colormap like you can :). What's your secret :D?

**Comment by hopehhchen** [comment]
Sorry for the late reply!  The secret is to plot it on lognormal scale, and use precentiles to adjust the limits:

```
import matplotlib.colors as colors
import matplotlib.pyplot as plt
import numpy as np

plt.imshow(image,
           cmap = ‘gray’,
           norm = colors.LogNorm(vmin = np.nanmin(image_plt),
                                 vmax = np.nanpercentile(image_plt, 95.)))
```

Can't wait to see the plot!

**Comment by hopehhchen** [comment]
Sorry for my bad naming!  In the mock code, `image` and `image_plt` should be the same thing that is the 2D array to be plotted.

**Comment by catherinezucker** [comment]
@hopehhchen -- Here's the old RadFil version of the figure above that you made using new RadFil. I think the cuts and peaks are definitely slightly off, but I think I like new RadFil better. As you said, there might be a difference in how we select cuts too close to the edge of the spine. But I *thought* we both just did 1:-1...

Here's old RadFil:


        #If pts_mask!=None, only sample points which fall inside pts_mask. Otherwise, sample along entire spine
        if pts_mask!=None:
            pts_mask=np.where(pts_mask[yfit[1:-1:samp_int].astype(int),xfit[1:-1:samp_int].astype(int)]==1)
        else:
            pts_mask=np.ones((yfit[1:-1:samp_int].shape)).astype(bool)

        self.xfit=xfit[1:-1:samp_int][pts_mask]
        self.yfit=yfit[1:-1:samp_int][pts_mask]
        self.points=xfit[1:-1:samp_int][pts_mask]
        self.fprime=yprime[1:-1:samp_int][pts_mask]/xprime[1:-1:samp_int][pts_mask]
        self.m=-1.0/(yprime[1:-1:samp_int][pts_mask]/xprime[1:-1:samp_int][pts_mask])

And here's new RadFil:

      ```
            if (self.pts_mask is not None):
                pts_mask = ((self.pts_mask[np.round(yspline[1:-1:self.samp_int]).astype(int),
                                           np.round(xspline[1:-1:self.samp_int]).astype(int)]) &\
                            (self.mask[np.round(yspline[1:-1:self.samp_int]).astype(int),
                                       np.round(xspline[1:-1:self.samp_int]).astype(int)]))
            else:
                pts_mask = (self.mask[np.round(yspline[1:-1:self.samp_int]).astype(int),
                                      np.round(xspline[1:-1:self.samp_int]).astype(int)])

            # Prepare for extracting the profiles
            self.xspline = xspline[1:-1:self.samp_int][pts_mask]
            self.yspline = yspline[1:-1:self.samp_int][pts_mask]
            self.points = np.asarray(zip(self.xspline, self.yspline))
            self.fprime = np.asarray(zip(xprime[1:-1:self.samp_int][pts_mask], yprime[1:-1:self.samp_int][pts_mask]))
      ```

At this point, I am convinced that new RadFil is working great--it's mostly just that I want to understand the small discrepancies out of curiosity.

[Old_RadFil_Fil8_Cuts.pdf](https://github.com/catherinezucker/radfil/files/1221038/Old_RadFil_Fil8_Cuts.pdf)

**Comment by hopehhchen** [comment]
@catherinezucker, thanks for checking it!  Yes, I think it's worthwhile looking into every discrepancy, and I agree that it's working pretty good now.  Tomorrow I'll implement the changes that will make the codes work consistently when `cut = False` and `cut = True`.

Then, the last two things are just 1) making sure that the new and the old versions produce similar enough fitted parameters (and that we know the reason to the discrepancy), and 2) making sure we are happy with the new plotting style you implemented.  Let's aim at publishing the codes before the end of August (or at the latest by early September)!

**Comment by catherinezucker** [comment]
Sounds good! Plotting is still not fully implemented on my end for all the
different options but I will work on it more this week so it looks good in
all cases. Thanks Hope!

**Comment by hopehhchen** [comment]
The peak finding is finalized.  See #12 for fixing the behavior of the mask when `cut = True` and `cut = False`.
