### ISSUE TITLE
Background Subtraction Error?

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#15]
I think there might be a background subtraction error produced via the same code snippet shown in #14 . I'm getting background subtraction slopes that are essentially flat, when it is clearly skewed. Not sure what is going on here. Do you think it's something with the sigma-clipping, or is there just a bug somewhere? It's weird because it's only reproducible in skewed profiles (where one end is higher than the other). Flat profiles are fine...

[bg_sub_bug.pdf](https://github.com/catherinezucker/radfil/files/1219435/bg_sub_bug.pdf)

**Comment by catherinezucker** [comment]
Wait still might be a bug, but I think I found an unrelated plotting bug...hold on

**Comment by hopehhchen** [comment]
The PDF you attached looks like a plotting problem to me (the fitted parameters seem normal).  Just in case, please check if you used the fitted `astropy.modeling` models for predictions ([astropy documentation here](http://docs.astropy.org/en/stable/modeling/#simple-1-d-model-fitting)).  Let me know if it is a plotting bug.  Thanks!

**Comment by catherinezucker** [comment]
Yes, it is! It is my own plotting bug. I just fixed it and will push the new version through. Sorry and thanks for catching it!

**Comment by catherinezucker** [comment]
Here we go :)

[bg_sub_bug.pdf](https://github.com/catherinezucker/radfil/files/1219438/bg_sub_bug.pdf)

**Comment by catherinezucker** [comment]
New version has been pushed through. Closing this...

**Comment by hopehhchen** [comment]
Great!  It seems that there's still room for fine tuning sigma clipping, but it shouldn't change the bg subtraction by much.  We can look into that later.
