### ISSUE TITLE
Another bug in build_profile?

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#17]
Hi @hopehhchen ,

I think I might have found another bug in the newest version of build_profile.

img,hdr=fits.getdata("./Fil10_Bug_Data/HIGAL_L_Fil10_N.fits",header=True)
mask=fits.getdata("./Fil10_Bug_Data/Fil10_filfind_mask.fits")
dist=3200.

fil=radfil_class.radfil(img,filmask.astype(bool),header=hdr,distance=dist,padsize=padsize,filspine=fits.getdata(lpath+"Skeleton_Longpaths/"+filname+"_longpath.fits"))
fil.build_profile(pts_mask=pts_mask,cutdist=5.0,samp_int=int(np.round(0.5/imgscale)))
fil.fit_profile(fitfunc="Plummer",fitdist=4.0,bgdist=(3.0,4.0))
fig=plt.figure()
plt.scatter(fil.xall,fil.yall)

And then I get a single cut that looks like this:

<img width="497" alt="screen shot 2017-08-17 at 4 46 55 pm" src="https://user-images.githubusercontent.com/18339657/29433091-e07aa0ae-836b-11e7-959c-4b2875580f29.png">

Do you think this is user error or an issue with the masking? And do you think it will affect the fit results? I am trying to get another draft out to Alyssa before I leave for Chile on Saturday. After I finish implementing all the other changes on the draft I can come back to this, but if you have time to take a look tonight that would be great too :)

**Comment by hopehhchen** [comment]
Ha, this looks like a real one!  Could you please pass me the data (the image, the mask, and the spine), @catherinezucker?  I don't think the fit will be affected by a lot but it surely will, since the code does not remove outliers when fitting for the profile.  I'll try to sort it out tonight. :)

**Comment by catherinezucker** [comment]
Actually, I think this might be user error after all. Let me check something again before you do anything :).

Best,
Catherine

**Comment by hopehhchen** [comment]
It looks like those zero points could be due to padding to me.  Anyway, let me know if you think it's just bad input parameters.  Thanks!

**Comment by catherinezucker** [comment]
Yeah, I just tested this and it definitely has to do with pad. Do you think there's any reason to keep pad? It seems like it might just cause bad things to happen. It was necessary before because of how I was building profiles, but not I think it's defunct. Are there any cases you can think of where people would want to add zeros in the new version?

**Comment by hopehhchen** [comment]
No, I actually wanted to remove it when I started the new RadFil.  If you agree, I'll go ahead and remove padding all together.

**Comment by catherinezucker** [comment]
Yeah, I agree. If it's easy for you, that would be great. Otherwise, I can
do it. Thanks so much, Hope!!

**Comment by hopehhchen** [comment]
I can do it.  Thanks for pointing this out!

**Comment by hopehhchen** [comment]
Padding is now completely removed.  See 8788b3b600f896cd0217afa153355913555737f7.

**Comment by catherinezucker** [comment]
Perfect! Thanks, Hope!
