### ISSUE TITLE
Problem with curveorder

### ISSUE THREAD

**Issue by hopehhchen** [catherinezucker/radfil#21]
For B5, the list generated by curveorder is wrong with the first two points seemingly backwards.  HC will explain more later.

**Comment by catherinezucker** [comment]
You edited curveorder recently right? Can you check if the problem still
exists with the original version before the deletions?

**Comment by hopehhchen** [comment]
I did check.  The problem is there regardless of which version I use.  (The edit on `curveorder` was just to remove the codes that weren't really used.)  It doesn't seem to affect the spline calculation, but it is annoying.

As in the attached screenshot, the points should obviously be (99, 34), (99, 33), and (99, 32), but the first two are backwards.
<img width="1098" alt="screen shot 2017-08-23 at 3 38 57 pm" src="https://user-images.githubusercontent.com/5449218/29634868-37f913a4-8819-11e7-8344-a755b801a41e.png">

**Comment by hopehhchen** [comment]
It's confirmed.  The correct order is not even in the list of paths found in the network graph at all.  We should think of a way to resolve this.

**Comment by catherinezucker** [comment]
Thanks for catching this, Hope. That seems like a possibility. And it
doesn't seem to be limited to B5 (I just tried it on one of mine and the
same problem exists). Maybe the path shown really is the shortest path
between all the nodes, which is how the order is calculated (see
https://stackoverflow.com/questions/37742358/sorting-
points-to-form-a-continuous-line). This is something we could easily
test--measure the total length of the connected line in the original
configuration and in the configuration where the order of the first two
points are switched. If this only manifests in this situation, we could
easily build in a catch safe to account for this.

**Comment by hopehhchen** [comment]
I just went over again how the nearest neighbor algorithm is run, and I think I have a pretty good guess of the reason and a possible solution.

### Possible Reason

Since the nearest neighbor does not care about the permutation of two neighboring points, it's likely that only one of the two such permutations (for a given pair) will be included in the *k-neighbor* graph.  For example, only one of the following orders will be in the network based on the sparse matrix produced by `NearestNeighbor(2)`:
```
[1, 2, 3, 4, 5]
```
or
```
[1, 2, 3, 5, 4]
```

### Possible Solution

Since only permutation at one of the two ends of a series can have a cost (distance) that is lower than other possible permutations (*e.g.* one permutation for two elements in the middle of the series, or two permutations for the pairs at *both* ends of the series), we can test whether the cost of the orders obtained by permuting one of the two end element pairs in `opt_order` is lower than the cost of the original `opt_order`.  For example, if `opt_order` is
```
[1, 2, 3, 4, 5]
```
we can test whether one of the following orders has a lower cost:
```
[2, 1, 3, 4, 5]
```
or
```
[1, 2, 3, 5, 4]
```

This solution will not noticeably slow down the code.

**Comment by hopehhchen** [comment]
I have implemented the solution described above.  @catherinezucker, it would be great if you could take a look at your filaments and see if the problem is still there.  Thanks!

**Comment by hopehhchen** [comment]
HC thinks this is resolved.  The implementation is in 93b5667285f950e4aca8592545e4cded94b50562.
