### ISSUE TITLE
Should the mask be an optional input? Theoretically you don't need it if you want shift=False

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#24]
Thoughts @hopehhchen?

**Comment by hopehhchen** [comment]
I'll review the codes tomorrow, but I thought a mask is needed anyway for deriving the spine.  Is that correct, @catherinezucker?

**Comment by catherinezucker** [comment]
Yeah, it is. But if they input a pre-computed spine via e.g. disperse, they
won't need it. It's a very special use case though.

**Comment by hopehhchen** [comment]
Good point!  How about raising an error only when both `mask` and `filspine` are `None`, and making both of them optional?

**Comment by catherinezucker** [comment]
Sounds good; I will add this in and push it along with the latest version I
am working on. Also, shift would need to be False as well (otherwise you
can't reasonably search for the peak column density pixel along each cut).
So mask can only be optional when filspine is inputed and shift=False. What
do you think? Can you see this happening enough that it would be good to
make it optional?

**Comment by hopehhchen** [comment]
Ah, I see what you mean now.  I think this should be considered together with the removal of `cutdist`.  If there is a `cutdist`, then I think it is reasonable to find the maximum along each cut within `cutdist`, and it should be fine.  We can raise a warning anyway.

I think what could be sensible to do might be raising an error when both `mask` and `filspine` are `None` in `__init__`, and raising a warning (or a separate error if the solution above doesn't make sense) for wrong setups (e.g. `shift = False`) in `build_profile`.  How does that sound?

**Comment by catherinezucker** [comment]
Sounds good. Let's talk about this on Thursday and maybe implement then? I
already have an almost there version (minus searching for max col density
confined within cutdist, which I think is a good solution). Thanks :)

**Comment by hopehhchen** [comment]
Awesome!  Thanks!

**Comment by catherinezucker** [comment]
I just pushed this commit, along with some other changes. Thanks :)

**Comment by catherinezucker** [comment]
Let me know if you find bugs!
