### ISSUE TITLE
Prepare setup.py

### ISSUE THREAD

**Issue by hopehhchen** [catherinezucker/radfil#26]
Penny suggested following the steps listed [here](http://peterdowns.com/posts/first-time-with-pypi.html).

**Comment by hopehhchen** [comment]
Hi, @catherinezucker, I have updated the setup files (eea6d2795b3935ebee7468dba1f6ea7ae2d76575), and there are only a few more things to do before publishing the codes to PyPi.  Since the codes are hosted in your github repo, I need your help:

1. Merge the Developer branch. (When you feel ready! 😄)
2. Create accounts on [PyPi Live](https://pypi.python.org/pypi?%3Aaction=register_form) and on [PyPi Test](https://testpypi.python.org/pypi?%3Aaction=register_form).
3. Create a .pypirc on your own home directory.  This is optional and is only for your own convenience (so you don't have to type/remember your account when the time comes).  An example is [here](http://peterdowns.com/posts/first-time-with-pypi.html) and below:
```
[distutils]
index-servers =
  pypi
  pypitest

[pypi]
repository=https://pypi.python.org/pypi
username=your_username
password=your_password

[pypitest]
repository=https://testpypi.python.org/pypi
username=your_username
password=your_password
``` 
4. Make a tag in the repo by running the following command in your repo, if 0.1 would be the version name for the submission.
```
git tag 0.1 -m "Adds a tag so that we can put this on PyPI. [other comments]"
```
5. Test by first submitting to [PyPi Test](https://testpypi.python.org/pypi).  This can be done by running the following commands in your repo:
```
python setup.py register -r pypitest
python setup.py sdist upload -r pypitest
```
6. If no error shows up, go ahead and submit it to the real site, [PyPi Live](https://pypi.python.org/pypi).  Please run:
```
python setup.py register -r pypi
python setup.py sdist upload -r pypi
```

I have updated the setup files, so there should be no problem.  Please let me know if you need help.  You can also consult the [tutorial Penny sent us](http://peterdowns.com/posts/first-time-with-pypi.html).

**Comment by catherinezucker** [comment]
Sounds good, thanks Hope! I will take a final look at it tonight/tomorrow
morning and then we can probably publish tomorrow? I still want to add a
few more details to the tutorial and do a final check of the documentation,
but I think we should be good. Is there anything else you think we need to
do before putting it on pypi?

**Comment by hopehhchen** [comment]
Yes, I agree that we should go over the documentation to make sure that it's up to date.  The only other thing I notice is that the model (or the background fit) is sometimes not smooth enough (see the image below).  I'll get to it tonight. :)

![plotting example](https://user-images.githubusercontent.com/5449218/30353960-89ef50a4-97f7-11e7-8dc6-ea5cc6a2557c.png)

**Comment by hopehhchen** [comment]
Updated with e45346576c5cc4b5daa22c59b33919ddae30b0d4.  Below is an example using the same data (Musca).

![plotting example](https://user-images.githubusercontent.com/5449218/30355089-f58ecce8-97fe-11e7-99f9-fc0737b93ca4.png)

**Comment by catherinezucker** [comment]
That looks a lot better, thanks! See you tomorrow...we can talk more then!

**Comment by catherinezucker** [comment]
I just merged the Developer branch @hopehhchen . The master should be up to date now. Also added more details to the documentation and a few more in the tutorial as well!

**Comment by catherinezucker** [comment]
I added the warning re: cut=False, pushed it to github, and then tested the package on pypi test. That was successfully, so then I uploaded it to pypi live. It should now be downloadable via pip install radfil. We're at version 0.1.0! I will add this to the README @hopehhchen
