### ISSUE TITLE
How to make a filspine file to fit the option in the function inradfil_class.radfil?

### ISSUE THREAD

**Issue by hongliliu** [catherinezucker/radfil#32]
Dear Zucker and Chen,
        Recent days, I was trying to identify the main filament from a column density image following the tutorial you gave. However, I found the identified filament spine is not as good as I expected when using the option MASK in the function inradfil_class.radfil. So, I would like to have a try to use the option FILSPINE by invoking a user-defined filspine, which is supposed to be a Boolean array same as the input image in size. However, I still don't know how to make such array (or the filspine fits file) based on the column density map even though I made some attempts. So, if possible, could you help give an example of how to prepare for a user-defined filspine? Thank you very much in advance for your kind help.
        Best regards,
Hongli

**Comment by catherinezucker** [comment]
Hi Hongli,

Are you sure you definitely don't want to use the mask input option to create the spine? I've jotted down a little example of how to make a mask using a column density map by defining a column density threshold. You might play around with different thresholds (and also try smoothing the map) and see if any of those work to create a spine (https://github.com/catherinezucker/CZ_Code_Snippets/blob/master/Get_Mask_Example.ipynb). I didn't include too many comments, so let me know if something is unclear. 

Beyond that, you could try using DisPerSE (http://www2.iap.fr/users/sousbie/web/html/indexd41d.html) to create the spines. However, I've never actually done it, so I can't provide any useful documentation. 

If your data are publicly available, I'm happy to take a look and see if I can help.

Best,
Catherine

**Comment by hongliliu** [comment]
Hi Catherine,

	Thank you very much for your reply along with the useful comments. Over past a few days, I have tried with different column densities to make the mask. Finally, I have obtained a spine that looks reasonable. The RadFil is very useful to me, and thus I will use, and cite it in our coming work. Thank you again for your kind help.

	Cheers,
Hongli





-Chile Fondecyt Postdoctoral Fellowship
-University of Concepcion

**Comment by catherinezucker** [comment]
No worries -- glad it was helpful! Looking forward to reading your manuscript!

~ Catherine
