### ISSUE TITLE
Filament Spine Dimension Error

### ISSUE THREAD

**Issue by ohseanuconn** [catherinezucker/radfil#33]
Dear Catherine,

When making the filament spine in the Radfil Tutorial using the code shown below,

radobj.make_fil_spine(beamwidth=36.3,verbose=False)
fits.writeto("./Tutorial_Data/Musca_spine.fits", radobj.filspine.astype(int), overwrite=True)

I am getting a 'TypeError: only dimensionless scalar quantities can be converted to Python scalars'. How can I work around this error to create my filament spine?

Thank you so much,
Sean

**Comment by catherinezucker** [comment]
Hi Sean,

Can you send me a full error message, and also what version of astropy you
are using?

Thanks,
Catherine

**Comment by ohseanuconn** [comment]
Hi Catherine,

I'm using Astropy Version 4.
The full error message is really long so I attached it below.
[filament spine error.pdf](https://github.com/catherinezucker/radfil/files/4309297/filament.spine.error.pdf)

Thanks again,
Sean

**Comment by catherinezucker** [comment]
Hi Sean,

You'll need to update your version of the filfinder package, which is a radfil dependency. Type this into your terminal:

pip install git+https://github.com/e-koch/FilFinder.git

Then the tutorial should run for you.

Best,
Catherine

**Comment by ohseanuconn** [comment]
Hi Catherine,

I'm unfortunately still getting the same error message.
I also tried uninstalling and reinstalling the filfinder package but again got the same error.

Best, 
Sean

**Comment by catherinezucker** [comment]
Hi Sean,

When you type this...

import fil_finder
print(fil_finder.__version__)

Into your jupyter notebook, what does it say for the version?

~ Catherine

**Comment by ohseanuconn** [comment]
It says Version 1.6.

**Comment by catherinezucker** [comment]
Hi Sean,

It looks like your filfinder package didn't actually get updated to
the latest version on GitHub. That's the problem. You'll need to
update to 2.0.dev913. "pip install fil_finder" won't work. If the
command I gave you also won't work (pip install
git+https://github.com/e-koch/FilFinder.git) you can try downloading
the directory from GitHub and running "python setup.py install" in the
top level of the directory to install the latest version.

Best,
Catherine

**Comment by ohseanuconn** [comment]
Hi Catherine,

Installing from the repository worked! It is now working with version 2.0.dev0.
Thank you so much!

Best,
Sean

**Comment by catherinezucker** [comment]
Yay! You're welcome. I'll also ask Eric (the FilFinder developer) to see if it's possible to update pypi.
