### ISSUE TITLE
What happened to the "local mask width" attribute returned by build profile?

### ISSUE THREAD

**Issue by catherinezucker** [catherinezucker/radfil#4]
Line 324 in radfil_class.py
"""
 distpc: numpy.ndarray
            A numpy array containing the physical size of each "local width" cut. Can take
            the mean/median to determine representative width of the filament mask
 """

It is listed as an attribute accessible after build_profile, but doesn't exist anymore, and I use it in my current large-scale filament analysis. I also can't find it embedded in any of the other attributes. If it's not there anymore, I think we need to add it back in, as it is a critical width determination when the radial profile fitting is not possible. Do you think you might be able to do this @hopehhchen , since I'm still working my way through your code revision and not familiar with all the new variable names you've chosen yet? Thanks :).

**Comment by hopehhchen** [comment]
Makes sense.  I'll do it.

**Comment by catherinezucker** [comment]
Thanks so much!!

**Comment by hopehhchen** [comment]
Done.  See 1eba7c120861156581b91fbef46f696e0a79de23.  The "local mask width" is stored under the key `mask_width` in `dictionary_cuts`.  This is only done when `cutting = True`.
